// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package grpc

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// v1.0.0
// protocol
type Proto struct {
	Ver                  int32    `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Op                   int32    `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Seq                  int32    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Body                 []byte   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proto) Reset()         { *m = Proto{} }
func (m *Proto) String() string { return proto.CompactTextString(m) }
func (*Proto) ProtoMessage()    {}
func (*Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proto.Unmarshal(m, b)
}
func (m *Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proto.Marshal(b, m, deterministic)
}
func (m *Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proto.Merge(m, src)
}
func (m *Proto) XXX_Size() int {
	return xxx_messageInfo_Proto.Size(m)
}
func (m *Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_Proto.DiscardUnknown(m)
}

var xxx_messageInfo_Proto proto.InternalMessageInfo

func (m *Proto) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Proto) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *Proto) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Proto) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PushMsgReq struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	ProtoOp              int32    `protobuf:"varint,3,opt,name=protoOp,proto3" json:"protoOp,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (m *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(m, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *PushMsgReq) GetProtoOp() int32 {
	if m != nil {
		return m.ProtoOp
	}
	return 0
}

func (m *PushMsgReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type PushMsgReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReply) Reset()         { *m = PushMsgReply{} }
func (m *PushMsgReply) String() string { return proto.CompactTextString(m) }
func (*PushMsgReply) ProtoMessage()    {}
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PushMsgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReply.Unmarshal(m, b)
}
func (m *PushMsgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReply.Marshal(b, m, deterministic)
}
func (m *PushMsgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReply.Merge(m, src)
}
func (m *PushMsgReply) XXX_Size() int {
	return xxx_messageInfo_PushMsgReply.Size(m)
}
func (m *PushMsgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReply proto.InternalMessageInfo

type BroadcastReq struct {
	ProtoOp              int32    `protobuf:"varint,1,opt,name=protoOp,proto3" json:"protoOp,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Speed                int32    `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReq) Reset()         { *m = BroadcastReq{} }
func (m *BroadcastReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastReq) ProtoMessage()    {}
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *BroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReq.Unmarshal(m, b)
}
func (m *BroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReq.Marshal(b, m, deterministic)
}
func (m *BroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReq.Merge(m, src)
}
func (m *BroadcastReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastReq.Size(m)
}
func (m *BroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReq proto.InternalMessageInfo

func (m *BroadcastReq) GetProtoOp() int32 {
	if m != nil {
		return m.ProtoOp
	}
	return 0
}

func (m *BroadcastReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

func (m *BroadcastReq) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type BroadcastReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReply) Reset()         { *m = BroadcastReply{} }
func (m *BroadcastReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastReply) ProtoMessage()    {}
func (*BroadcastReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *BroadcastReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReply.Unmarshal(m, b)
}
func (m *BroadcastReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReply.Marshal(b, m, deterministic)
}
func (m *BroadcastReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReply.Merge(m, src)
}
func (m *BroadcastReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastReply.Size(m)
}
func (m *BroadcastReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReply proto.InternalMessageInfo

type BroadcastRoomReq struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRoomReq) Reset()         { *m = BroadcastRoomReq{} }
func (m *BroadcastRoomReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastRoomReq) ProtoMessage()    {}
func (*BroadcastRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *BroadcastRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRoomReq.Unmarshal(m, b)
}
func (m *BroadcastRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRoomReq.Marshal(b, m, deterministic)
}
func (m *BroadcastRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRoomReq.Merge(m, src)
}
func (m *BroadcastRoomReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastRoomReq.Size(m)
}
func (m *BroadcastRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRoomReq proto.InternalMessageInfo

func (m *BroadcastRoomReq) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *BroadcastRoomReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type BroadcastRoomReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRoomReply) Reset()         { *m = BroadcastRoomReply{} }
func (m *BroadcastRoomReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastRoomReply) ProtoMessage()    {}
func (*BroadcastRoomReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *BroadcastRoomReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRoomReply.Unmarshal(m, b)
}
func (m *BroadcastRoomReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRoomReply.Marshal(b, m, deterministic)
}
func (m *BroadcastRoomReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRoomReply.Merge(m, src)
}
func (m *BroadcastRoomReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastRoomReply.Size(m)
}
func (m *BroadcastRoomReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRoomReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRoomReply proto.InternalMessageInfo

type RoomsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomsReq) Reset()         { *m = RoomsReq{} }
func (m *RoomsReq) String() string { return proto.CompactTextString(m) }
func (*RoomsReq) ProtoMessage()    {}
func (*RoomsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *RoomsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomsReq.Unmarshal(m, b)
}
func (m *RoomsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomsReq.Marshal(b, m, deterministic)
}
func (m *RoomsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomsReq.Merge(m, src)
}
func (m *RoomsReq) XXX_Size() int {
	return xxx_messageInfo_RoomsReq.Size(m)
}
func (m *RoomsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomsReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomsReq proto.InternalMessageInfo

type RoomsReply struct {
	Rooms                map[string]bool `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoomsReply) Reset()         { *m = RoomsReply{} }
func (m *RoomsReply) String() string { return proto.CompactTextString(m) }
func (*RoomsReply) ProtoMessage()    {}
func (*RoomsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *RoomsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomsReply.Unmarshal(m, b)
}
func (m *RoomsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomsReply.Marshal(b, m, deterministic)
}
func (m *RoomsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomsReply.Merge(m, src)
}
func (m *RoomsReply) XXX_Size() int {
	return xxx_messageInfo_RoomsReply.Size(m)
}
func (m *RoomsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomsReply.DiscardUnknown(m)
}

var xxx_messageInfo_RoomsReply proto.InternalMessageInfo

func (m *RoomsReply) GetRooms() map[string]bool {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func init() {
	proto.RegisterType((*Proto)(nil), "goim.comet.Proto")
	proto.RegisterType((*Empty)(nil), "goim.comet.Empty")
	proto.RegisterType((*PushMsgReq)(nil), "goim.comet.PushMsgReq")
	proto.RegisterType((*PushMsgReply)(nil), "goim.comet.PushMsgReply")
	proto.RegisterType((*BroadcastReq)(nil), "goim.comet.BroadcastReq")
	proto.RegisterType((*BroadcastReply)(nil), "goim.comet.BroadcastReply")
	proto.RegisterType((*BroadcastRoomReq)(nil), "goim.comet.BroadcastRoomReq")
	proto.RegisterType((*BroadcastRoomReply)(nil), "goim.comet.BroadcastRoomReply")
	proto.RegisterType((*RoomsReq)(nil), "goim.comet.RoomsReq")
	proto.RegisterType((*RoomsReply)(nil), "goim.comet.RoomsReply")
	proto.RegisterMapType((map[string]bool)(nil), "goim.comet.RoomsReply.RoomsEntry")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x89, 0x9d, 0x9f, 0x69, 0xa8, 0xc2, 0x28, 0x8a, 0x8c, 0x55, 0x51, 0xf0, 0x85, 0x1e,
	0xa8, 0x2b, 0x05, 0x21, 0xaa, 0xf6, 0x44, 0xa0, 0x07, 0x0e, 0x15, 0xd1, 0x72, 0xe3, 0x96, 0x1f,
	0xb3, 0x8d, 0x48, 0xba, 0x5b, 0xaf, 0x53, 0xc9, 0x0f, 0xc0, 0x3b, 0x70, 0xe4, 0xc9, 0x78, 0x80,
	0x3e, 0x05, 0x3b, 0xb3, 0x26, 0x3f, 0x60, 0x50, 0xc5, 0xc1, 0xd6, 0x7c, 0xf3, 0xcd, 0xcc, 0x37,
	0x3b, 0x33, 0xd0, 0x1e, 0xeb, 0x79, 0xa2, 0x33, 0x95, 0x2b, 0x04, 0xa9, 0xe6, 0xcb, 0x64, 0xaa,
	0x96, 0x69, 0x1e, 0x1d, 0xcb, 0x79, 0x7e, 0xb5, 0x9a, 0x10, 0x3a, 0x91, 0x4a, 0xaa, 0x13, 0x0e,
	0x99, 0xac, 0x3e, 0x33, 0x62, 0xc0, 0x96, 0x4b, 0x8d, 0x0d, 0x04, 0x23, 0xae, 0xf1, 0x18, 0xea,
	0xb7, 0x69, 0x16, 0x7a, 0x4f, 0xbd, 0xa3, 0x60, 0xd8, 0xbc, 0xfb, 0x71, 0x48, 0x50, 0xd0, 0x0f,
	0xfb, 0x50, 0x53, 0x3a, 0xac, 0x31, 0xd3, 0xb0, 0x8c, 0x45, 0xc2, 0x7e, 0x94, 0x62, 0xd2, 0x9b,
	0xb0, 0xbe, 0x49, 0xb1, 0x50, 0xd0, 0x0f, 0x0f, 0xc0, 0x9f, 0xa8, 0x59, 0x11, 0xfa, 0x96, 0xeb,
	0x0c, 0x5b, 0x96, 0x63, 0x2c, 0xf8, 0x1f, 0x37, 0x21, 0xb8, 0x58, 0xea, 0xbc, 0x88, 0xa7, 0x00,
	0xa3, 0x95, 0xb9, 0xba, 0x34, 0x52, 0xd8, 0x24, 0x04, 0xff, 0x4b, 0x5a, 0x18, 0xdb, 0x43, 0xfd,
	0xa8, 0x2d, 0xd8, 0xc6, 0x10, 0x9a, 0xdc, 0xe8, 0x07, 0xed, 0x74, 0xc4, 0x2f, 0x88, 0xcf, 0x21,
	0x60, 0x93, 0x1b, 0xdb, 0x1b, 0x3c, 0x4a, 0x36, 0x43, 0x48, 0xf8, 0x49, 0xc2, 0xf1, 0xf1, 0x3e,
	0x74, 0xd6, 0x22, 0x7a, 0x51, 0xc4, 0x12, 0x3a, 0xc3, 0x4c, 0x8d, 0x67, 0xd3, 0xb1, 0xc9, 0x49,
	0x76, 0x4b, 0xc2, 0xfb, 0x3f, 0x09, 0xec, 0x41, 0x60, 0x74, 0x9a, 0xce, 0xca, 0x1e, 0x1d, 0x88,
	0xbb, 0xb0, 0xbf, 0x25, 0x44, 0xd2, 0x1f, 0xa1, 0xbb, 0xf1, 0x28, 0xb5, 0x24, 0xf9, 0x3e, 0x34,
	0x32, 0x6b, 0xbe, 0x7f, 0xc7, 0xea, 0x6d, 0x51, 0xa2, 0xfb, 0xbf, 0xaf, 0x07, 0xf8, 0x5b, 0x51,
	0x92, 0x02, 0x68, 0x11, 0x30, 0x56, 0x22, 0xfe, 0xea, 0x01, 0x94, 0xc0, 0x52, 0xf8, 0x1a, 0x02,
	0xd2, 0x70, 0x83, 0xde, 0x1b, 0x3c, 0xdb, 0xae, 0xbc, 0x09, 0x73, 0xe6, 0xc5, 0x75, 0x9e, 0x15,
	0xc2, 0xc5, 0x47, 0xa7, 0x65, 0x19, 0x76, 0x62, 0x17, 0xea, 0x76, 0x45, 0x65, 0xd7, 0x64, 0xd2,
	0x18, 0x6e, 0xc7, 0x8b, 0x55, 0xca, 0x2d, 0xb7, 0x84, 0x03, 0x67, 0xb5, 0x53, 0xef, 0xcc, 0xff,
	0xf6, 0xfd, 0xf0, 0xc1, 0xe0, 0xae, 0x06, 0xc1, 0x5b, 0x92, 0xc1, 0x17, 0xe0, 0x8f, 0xe6, 0xd7,
	0x12, 0x77, 0x5e, 0xc5, 0x37, 0x11, 0xfd, 0xe9, 0xc2, 0x63, 0x9b, 0xb6, 0x50, 0x26, 0xbd, 0x67,
	0xf8, 0x39, 0x34, 0xcb, 0x85, 0x63, 0x7f, 0x67, 0x6a, 0xeb, 0x53, 0x8b, 0xc2, 0x4a, 0x3f, 0x0d,
	0xe7, 0x0d, 0xb4, 0xd7, 0xd3, 0xc4, 0x9d, 0xb0, 0xed, 0xa3, 0x89, 0xa2, 0xbf, 0x30, 0x54, 0xe2,
	0x12, 0x1e, 0xee, 0x2c, 0x04, 0x0f, 0xaa, 0x83, 0xdd, 0x01, 0x44, 0x4f, 0xfe, 0xc1, 0x52, 0xb9,
	0x57, 0x10, 0xf0, 0xd4, 0xb1, 0x57, 0xb1, 0xa8, 0x9b, 0xa8, 0x5f, 0xbd, 0xbe, 0x61, 0xeb, 0x53,
	0x23, 0x39, 0x97, 0x99, 0x9e, 0x4e, 0x1a, 0x7c, 0x27, 0x2f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x2d, 0xc6, 0x53, 0xff, 0x32, 0x04, 0x00, 0x00,
}
